# Generated by Django 5.1.6 on 2025-06-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_appointment_doctor"),
        ("doctor", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments_patient",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="available_doctors",
            field=models.ManyToManyField(blank=True, to="doctor.doctor"),
        ),
    ]
